/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JTextFieldDateEditor;
import model.beans.Aluno;
import model.beans.CoOrientacao;
import model.beans.Pessoa;
import model.beans.TrabalhoConclusao;
import model.dao.AlunoDao;
import model.dao.CoOrientacaoDao;
import model.dao.PessoaDao;
import model.dao.TrabalhosDao;

/**
 *
 * @author Antonio
 */
public class TelaTrabalhos extends javax.swing.JFrame {
        private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form TelaAlunos
     */
    public TelaTrabalhos() {
        initComponents();
        lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCrudTrabalho = new javax.swing.JPanel();
        jLabelCodigoTrabalho = new javax.swing.JLabel();
        jTextFieldCodTrabalho = new javax.swing.JTextField();
        jLabelCodAluno = new javax.swing.JLabel();
        jTextFieldCodAluno = new javax.swing.JTextField();
        jLabelTituloTrabalho = new javax.swing.JLabel();
        jLabelNumAluno = new javax.swing.JLabel();
        jTextFieldTituloTrabalho = new javax.swing.JTextField();
        jTextFieldNumAluno = new javax.swing.JTextField();
        jButtonSalvarTrabalho = new javax.swing.JButton();
        jButtonAtualizarTrabalho = new javax.swing.JButton();
        jButtonExcluirTrabalho = new javax.swing.JButton();
        jLabelOrientador = new javax.swing.JLabel();
        jTextFieldOrientador = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jDateChooserDataApresentacao = new com.toedter.calendar.JDateChooser();
        jLabelCodTrabalhoAtual = new javax.swing.JLabel();
        jPanelTabelaTrabalho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaTrabalhos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trabalhos");
        setResizable(false);

        jLabelCodigoTrabalho.setText("Código:");

        jLabelCodAluno.setText("Código do Aluno:");

        jLabelTituloTrabalho.setText("Título:");

        jLabelNumAluno.setText("Número do Aluno:");

        jButtonSalvarTrabalho.setText("Salvar");
        jButtonSalvarTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarTrabalhoActionPerformed(evt);
            }
        });

        jButtonAtualizarTrabalho.setText("Atualizar");
        jButtonAtualizarTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTrabalhoActionPerformed(evt);
            }
        });

        jButtonExcluirTrabalho.setText("Excluir");
        jButtonExcluirTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTrabalhoActionPerformed(evt);
            }
        });

        jLabelOrientador.setText("Orientador:");

        jTextFieldOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrientadorActionPerformed(evt);
            }
        });

        jLabelData.setText("Data da Apresentação:");

        javax.swing.GroupLayout jPanelCrudTrabalhoLayout = new javax.swing.GroupLayout(jPanelCrudTrabalho);
        jPanelCrudTrabalho.setLayout(jPanelCrudTrabalhoLayout);
        jPanelCrudTrabalhoLayout.setHorizontalGroup(
            jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonSalvarTrabalho)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAtualizarTrabalho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirTrabalho)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCodTrabalhoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelOrientador)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldOrientador))
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelCodigoTrabalho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCodTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelCodAluno)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelNumAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserDataApresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addComponent(jLabelTituloTrabalho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTituloTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelCrudTrabalhoLayout.setVerticalGroup(
            jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                        .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigoTrabalho)
                            .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTituloTrabalho)
                                .addComponent(jTextFieldTituloTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCodTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCrudTrabalhoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodAluno)
                                    .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNumAluno)
                                        .addComponent(jTextFieldNumAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOrientador)
                            .addComponent(jTextFieldOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelData)))
                    .addComponent(jDateChooserDataApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSalvarTrabalho)
                    .addComponent(jLabelCodTrabalhoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCrudTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAtualizarTrabalho)
                        .addComponent(jButtonExcluirTrabalho)))
                .addContainerGap())
        );

        jTableTabelaTrabalhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Data da apresentação", "Código aluno", "Número aluno", "Código orientador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTabelaTrabalhos.getTableHeader().setReorderingAllowed(false);
        jTableTabelaTrabalhos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaTrabalhosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaTrabalhos);

        javax.swing.GroupLayout jPanelTabelaTrabalhoLayout = new javax.swing.GroupLayout(jPanelTabelaTrabalho);
        jPanelTabelaTrabalho.setLayout(jPanelTabelaTrabalhoLayout);
        jPanelTabelaTrabalhoLayout.setHorizontalGroup(
            jPanelTabelaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanelTabelaTrabalhoLayout.setVerticalGroup(
            jPanelTabelaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCrudTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTabelaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCrudTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTabelaTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarTrabalhoActionPerformed
        // TODO add your handling code here:
//        String data = jDateChooser1.toString();
//        java.util.Date parsed = sdf.parse(data);
//	Date sql = new Date(parsed.getTime());
        if (verificaCampos() == true) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }else{
            TrabalhoConclusao trabalho = new TrabalhoConclusao();
            TrabalhosDao tdao = new TrabalhosDao();

            CoOrientacao coOrientacao = new CoOrientacao();
            CoOrientacaoDao coDao = new CoOrientacaoDao();

            trabalho.setCodTrabalho(Integer.parseInt(jTextFieldCodTrabalho.getText()));
            trabalho.setTitulo(jTextFieldTituloTrabalho.getText());
            trabalho.setCodPessoaAluno(Integer.parseInt(jTextFieldCodAluno.getText()));
            trabalho.setCodPessoaOrientador(Integer.parseInt(jTextFieldOrientador.getText()));
            trabalho.setNumAluno(Integer.parseInt(jTextFieldNumAluno.getText()));
            trabalho.setDataDefesa(jDateChooserDataApresentacao.getDate());
    //trabalho.setDataDefesa(new java.util.Date());

            coOrientacao.setCodPessoa(Integer.parseInt(jTextFieldOrientador.getText()));
            coOrientacao.setCodTrabalho(Integer.parseInt(jTextFieldCodTrabalho.getText()));
            tdao.create(trabalho);
            coDao.create(coOrientacao);


            limpaCampos();
            lerTabela();
        }

//        DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//        Object[] dados = {jTextFieldCodAluno.getText(),jTextFieldNomeAluno.getText(),
//                          jTextFieldNumAluno.getText(), jTextFieldCursoAluno.getText()};
//        dtmAlunos.addRow(dados);

    }//GEN-LAST:event_jButtonSalvarTrabalhoActionPerformed

    public void lerTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableTabelaTrabalhos.getModel();
        modelo.setNumRows(0);
        TrabalhosDao tdao = new TrabalhosDao();

        for (ArrayList a : tdao.read2()) {
            modelo.addRow(new Object[]{
                a.get(0),
                a.get(1),
                a.get(2),
                a.get(3),
                a.get(4),
                a.get(5)

            });
        }
    }

    private void jButtonExcluirTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTrabalhoActionPerformed
        // TODO add your handling code here:
//        if (jTableTabelaAlunos.getSelectedRow() != -1){
//            DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//            dtmAlunos.removeRow(jTableTabelaAlunos.getSelectedRow());           
//        }else{
//            JOptionPane.showMessageDialog(null, "Selecione um aluno");
//        }

        if (jTableTabelaTrabalhos.getSelectedRow() != -1) {
            
            TrabalhoConclusao trabalho = new TrabalhoConclusao();
            TrabalhosDao tDao = new TrabalhosDao();
            

            
            trabalho.setCodTrabalho(Integer.parseInt(jTextFieldCodTrabalho.getText()));
            tDao.delete(trabalho);
            

            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno");
        }

        lerTabela();


    }//GEN-LAST:event_jButtonExcluirTrabalhoActionPerformed

    private void jButtonAtualizarTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTrabalhoActionPerformed
        // TODO add your handling code here:
        if (jTableTabelaTrabalhos.getSelectedRow() != -1) {
            
            if (verificaCampos() == true) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            }else{
            
                TrabalhoConclusao trabalho = new TrabalhoConclusao();
                TrabalhosDao trabDao = new TrabalhosDao();

                trabalho.setCodTrabalho(Integer.parseInt(jTextFieldCodTrabalho.getText()));
                trabalho.setTitulo(jTextFieldTituloTrabalho.getText());
                trabalho.setCodPessoaAluno(Integer.parseInt(jTextFieldCodAluno.getText()));
                trabalho.setNumAluno(Integer.parseInt(jTextFieldNumAluno.getText()));
                trabalho.setCodPessoaOrientador(Integer.parseInt(jTextFieldOrientador.getText()));
                trabalho.setDataDefesa(jDateChooserDataApresentacao.getDate());
                int codigo = Integer.parseInt(jLabelCodTrabalhoAtual.getText());

                trabDao.update(trabalho, codigo);

                limpaCampos();
                lerTabela();
            }

//            jTableTabelaAlunos.setValueAt(jTextFieldCodAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 0);
//            jTableTabelaAlunos.setValueAt(jTextFieldNomeAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 1);
//            jTableTabelaAlunos.setValueAt(jTextFieldNumAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 2);
//            jTableTabelaAlunos.setValueAt(jTextFieldCursoAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 3);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um trabalho na tabela.");
        }

    }//GEN-LAST:event_jButtonAtualizarTrabalhoActionPerformed

    private void jTextFieldOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrientadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrientadorActionPerformed

    private void jTableTabelaTrabalhosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaTrabalhosMouseClicked
        // TODO add your handling code here:
        if (jTableTabelaTrabalhos.getSelectedRow() != -1) {
            jTextFieldCodTrabalho.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(), 0).toString());
            jTextFieldTituloTrabalho.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(), 1).toString());
            jDateChooserDataApresentacao.setDate((java.util.Date) jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(),2));
            jTextFieldCodAluno.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(), 3).toString());
            jTextFieldNumAluno.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(), 4).toString());
            if (jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(),5).toString() != null){
                jTextFieldOrientador.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(),5).toString());
            }else{
                jTextFieldOrientador.setText("");
            }
            
            jLabelCodTrabalhoAtual.setText(jTableTabelaTrabalhos.getValueAt(jTableTabelaTrabalhos.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTableTabelaTrabalhosMouseClicked

    private boolean verificaCampos(){
        String campoCodigo = jTextFieldCodTrabalho.getText();
        String campoNome = jTextFieldTituloTrabalho.getText();
        String campoCodAluno = jTextFieldCodAluno.getText();
        String campoNumAluno = jTextFieldNumAluno.getText();
        String campoOrientador = jTextFieldOrientador.getText();
        //Date campoData = (Date) jDateChooserDataApresentacao.getDate();
        if (campoCodigo.isEmpty() || campoNome.isEmpty() || campoCodAluno.isEmpty() || campoNumAluno.isEmpty() || campoOrientador.isEmpty() || jDateChooserDataApresentacao.getDate() == null){
            return true;
        }else{
            return false;
        }
    }
 
    private void limpaCampos(){
        jTextFieldCodTrabalho.setText("");
        jTextFieldTituloTrabalho.setText("");
        jTextFieldCodAluno.setText("");
        jTextFieldNumAluno.setText("");
        jTextFieldOrientador.setText("");
        jDateChooserDataApresentacao.setDateFormatString("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTrabalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTrabalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTrabalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTrabalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTrabalhos().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarTrabalho;
    private javax.swing.JButton jButtonExcluirTrabalho;
    private javax.swing.JButton jButtonSalvarTrabalho;
    private com.toedter.calendar.JDateChooser jDateChooserDataApresentacao;
    private javax.swing.JLabel jLabelCodAluno;
    private javax.swing.JLabel jLabelCodTrabalhoAtual;
    private javax.swing.JLabel jLabelCodigoTrabalho;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelNumAluno;
    private javax.swing.JLabel jLabelOrientador;
    private javax.swing.JLabel jLabelTituloTrabalho;
    private javax.swing.JPanel jPanelCrudTrabalho;
    private javax.swing.JPanel jPanelTabelaTrabalho;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaTrabalhos;
    private javax.swing.JTextField jTextFieldCodAluno;
    private javax.swing.JTextField jTextFieldCodTrabalho;
    private javax.swing.JTextField jTextFieldNumAluno;
    private javax.swing.JTextField jTextFieldOrientador;
    private javax.swing.JTextField jTextFieldTituloTrabalho;
    // End of variables declaration//GEN-END:variables
}
