/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.Instituicao;
import model.dao.InstituicaoDao;

/**
 *
 * @author Antonio
 */
public class TelaInstituicao extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlunos
     */
    public TelaInstituicao() {
        initComponents();
        lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCrudInstituicao = new javax.swing.JPanel();
        jLabelCodigoInstituicao = new javax.swing.JLabel();
        jTextFieldCodInstituicao = new javax.swing.JTextField();
        jLabelNomeInstituicao = new javax.swing.JLabel();
        jTextFieldNomeInstituicao = new javax.swing.JTextField();
        jButtonSalvarInstituicao = new javax.swing.JButton();
        jButtonAtualizarInstituicao = new javax.swing.JButton();
        jButtonExcluirInstituicao = new javax.swing.JButton();
        jPanelTabelaDocente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaInstituicao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instituição");
        setResizable(false);

        jLabelCodigoInstituicao.setText("Código:");

        jLabelNomeInstituicao.setText("Nome:");

        jButtonSalvarInstituicao.setText("Salvar");
        jButtonSalvarInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarInstituicaoActionPerformed(evt);
            }
        });

        jButtonAtualizarInstituicao.setText("Atualizar");
        jButtonAtualizarInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarInstituicaoActionPerformed(evt);
            }
        });

        jButtonExcluirInstituicao.setText("Excluir");
        jButtonExcluirInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirInstituicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrudInstituicaoLayout = new javax.swing.GroupLayout(jPanelCrudInstituicao);
        jPanelCrudInstituicao.setLayout(jPanelCrudInstituicaoLayout);
        jPanelCrudInstituicaoLayout.setHorizontalGroup(
            jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudInstituicaoLayout.createSequentialGroup()
                .addGroup(jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrudInstituicaoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelCodigoInstituicao)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabelNomeInstituicao)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCrudInstituicaoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButtonSalvarInstituicao)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAtualizarInstituicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirInstituicao)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelCrudInstituicaoLayout.setVerticalGroup(
            jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudInstituicaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeInstituicao)
                    .addComponent(jTextFieldNomeInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoInstituicao))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarInstituicao)
                    .addGroup(jPanelCrudInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAtualizarInstituicao)
                        .addComponent(jButtonExcluirInstituicao)))
                .addGap(44, 44, 44))
        );

        jTableTabelaInstituicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTabelaInstituicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaInstituicaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaInstituicao);

        javax.swing.GroupLayout jPanelTabelaDocenteLayout = new javax.swing.GroupLayout(jPanelTabelaDocente);
        jPanelTabelaDocente.setLayout(jPanelTabelaDocenteLayout);
        jPanelTabelaDocenteLayout.setHorizontalGroup(
            jPanelTabelaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanelTabelaDocenteLayout.setVerticalGroup(
            jPanelTabelaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTabelaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCrudInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCrudInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTabelaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarInstituicaoActionPerformed
        // TODO add your handling code here:
        
        Instituicao instituicao = new Instituicao();
        InstituicaoDao instiDao = new InstituicaoDao();
        
        instituicao.setCodInstituicao(Integer.parseInt(jTextFieldCodInstituicao.getText()));
        instituicao.setNomeInstituicao(jTextFieldNomeInstituicao.getText());
        instiDao.create(instituicao);
        
        lerTabela();
        
        
        
//        DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//        Object[] dados = {jTextFieldCodAluno.getText(),jTextFieldNomeAluno.getText(),
//                          jTextFieldNumAluno.getText(), jTextFieldCursoAluno.getText()};
//        dtmAlunos.addRow(dados);
        
     
    }//GEN-LAST:event_jButtonSalvarInstituicaoActionPerformed

    public void lerTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTableTabelaInstituicao.getModel();
        modelo.setNumRows(0);
        InstituicaoDao instDao = new InstituicaoDao();       
        
        for (Instituicao i:instDao.read()){
            modelo.addRow(new Object[]{
            i.getCodInstituicao(),
            i.getNomeInstituicao()           
        });
        }  
    
    }    
    
    private void jButtonExcluirInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirInstituicaoActionPerformed
        // TODO add your handling code here:
//        if (jTableTabelaAlunos.getSelectedRow() != -1){
//            DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//            dtmAlunos.removeRow(jTableTabelaAlunos.getSelectedRow());           
//        }else{
//            JOptionPane.showMessageDialog(null, "Selecione um aluno");
//        }
        
         if (jTableTabelaInstituicao.getSelectedRow() != -1){
             
            Instituicao instituicao = new Instituicao();
            InstituicaoDao instiDao = new InstituicaoDao();
            
            instituicao.setCodInstituicao(Integer.parseInt(jTextFieldCodInstituicao.getText()));
            instiDao.delete(instituicao);        
            
            lerTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um aluno");
        }
               
        lerTabela();
        
    }//GEN-LAST:event_jButtonExcluirInstituicaoActionPerformed

    private void jTableTabelaInstituicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaInstituicaoMouseClicked
        // TODO add your handling code here:
        if (jTableTabelaInstituicao.getSelectedRow() != -1){
            jTextFieldCodInstituicao.setText(jTableTabelaInstituicao.getValueAt(jTableTabelaInstituicao.getSelectedRow(), 0).toString());
            jTextFieldNomeInstituicao.setText(jTableTabelaInstituicao.getValueAt(jTableTabelaInstituicao.getSelectedRow(), 1).toString());
                      
        }
        
    }//GEN-LAST:event_jTableTabelaInstituicaoMouseClicked

    private void jButtonAtualizarInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarInstituicaoActionPerformed
        // TODO add your handling code here:
        if (jTableTabelaInstituicao.getSelectedRow() != -1){
            
            Instituicao instituicao = new Instituicao();
            InstituicaoDao instiDao = new InstituicaoDao();
            
            instituicao.setCodInstituicao(Integer.parseInt(jTextFieldCodInstituicao.getText()));
            instituicao.setNomeInstituicao(jTextFieldNomeInstituicao.getText());
            instiDao.update(instituicao);

            lerTabela();
            
//            jTableTabelaAlunos.setValueAt(jTextFieldCodAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 0);
//            jTableTabelaAlunos.setValueAt(jTextFieldNomeAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 1);
//            jTableTabelaAlunos.setValueAt(jTextFieldNumAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 2);
//            jTableTabelaAlunos.setValueAt(jTextFieldCursoAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 3);

        }
        
    }//GEN-LAST:event_jButtonAtualizarInstituicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInstituicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInstituicao().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarInstituicao;
    private javax.swing.JButton jButtonExcluirInstituicao;
    private javax.swing.JButton jButtonSalvarInstituicao;
    private javax.swing.JLabel jLabelCodigoInstituicao;
    private javax.swing.JLabel jLabelNomeInstituicao;
    private javax.swing.JPanel jPanelCrudInstituicao;
    private javax.swing.JPanel jPanelTabelaDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaInstituicao;
    private javax.swing.JTextField jTextFieldCodInstituicao;
    private javax.swing.JTextField jTextFieldNomeInstituicao;
    // End of variables declaration//GEN-END:variables
}
