/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.Aluno;
import model.beans.Docente;
import model.beans.Pessoa;
import model.dao.AlunoDao;
import model.dao.DocenteDao;
import model.dao.PessoaDao;

/**
 *
 * @author Antonio
 */
public class TelaDocentes extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlunos
     */
    public TelaDocentes() {
        initComponents();
        lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCrudDocente = new javax.swing.JPanel();
        jLabelCodigoDocente = new javax.swing.JLabel();
        jTextFieldCodDocente = new javax.swing.JTextField();
        jLabelNumInstituicao = new javax.swing.JLabel();
        jTextFieldNumInstituicao = new javax.swing.JTextField();
        jLabelNomeDocente = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jTextFieldNomeDocente = new javax.swing.JTextField();
        jTextFieldNomeDepartamento = new javax.swing.JTextField();
        jButtonSalvarDocente = new javax.swing.JButton();
        jButtonAtualizarDocente = new javax.swing.JButton();
        jButtonExcluirDocente = new javax.swing.JButton();
        jLabelCodDocenteAtual = new javax.swing.JLabel();
        jPanelTabelaDocente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaDocentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Docentes");
        setResizable(false);

        jLabelCodigoDocente.setText("Código:");

        jLabelNumInstituicao.setText("Instituição:");

        jLabelNomeDocente.setText("Nome:");

        jLabelDepartamento.setText("Departamento:");

        jButtonSalvarDocente.setText("Salvar");
        jButtonSalvarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarDocenteActionPerformed(evt);
            }
        });

        jButtonAtualizarDocente.setText("Atualizar");
        jButtonAtualizarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarDocenteActionPerformed(evt);
            }
        });

        jButtonExcluirDocente.setText("Excluir");
        jButtonExcluirDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrudDocenteLayout = new javax.swing.GroupLayout(jPanelCrudDocente);
        jPanelCrudDocente.setLayout(jPanelCrudDocenteLayout);
        jPanelCrudDocenteLayout.setHorizontalGroup(
            jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                                .addComponent(jLabelCodigoDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                                .addComponent(jLabelNumInstituicao)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNumInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                                .addComponent(jLabelDepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNomeDepartamento))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrudDocenteLayout.createSequentialGroup()
                                .addComponent(jLabelNomeDocente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jTextFieldNomeDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonSalvarDocente)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonAtualizarDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirDocente)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCodDocenteAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanelCrudDocenteLayout.setVerticalGroup(
            jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodigoDocente)
                    .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNomeDocente)
                        .addComponent(jTextFieldNomeDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCodDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumInstituicao)
                            .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelDepartamento)
                                .addComponent(jTextFieldNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalvarDocente)
                            .addGroup(jPanelCrudDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonAtualizarDocente)
                                .addComponent(jButtonExcluirDocente))))
                    .addGroup(jPanelCrudDocenteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCodDocenteAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTableTabelaDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Instituição", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTabelaDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaDocentesMouseClicked(evt);
            }
        });
        jTableTabelaDocentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableTabelaDocentesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaDocentes);

        javax.swing.GroupLayout jPanelTabelaDocenteLayout = new javax.swing.GroupLayout(jPanelTabelaDocente);
        jPanelTabelaDocente.setLayout(jPanelTabelaDocenteLayout);
        jPanelTabelaDocenteLayout.setHorizontalGroup(
            jPanelTabelaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanelTabelaDocenteLayout.setVerticalGroup(
            jPanelTabelaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTabelaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCrudDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCrudDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTabelaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarDocenteActionPerformed
        // TODO add your handling code here:
        
        if (verificaCampos() == true){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }else{
        
            Pessoa pessoa = new Pessoa();
            PessoaDao pesDao = new PessoaDao();
            Docente docente = new Docente();
            DocenteDao docDao = new DocenteDao();

            pessoa.setCodPessoa(Integer.parseInt(jTextFieldCodDocente.getText()));
            pessoa.setNomePessoa(jTextFieldNomeDocente.getText());      
            pesDao.create(pessoa);

            docente.setCodPessoa(pessoa.getCodPessoa());
            docente.setCodInstituicao(Integer.parseInt(jTextFieldNumInstituicao.getText()));
            docente.setNomeDepartamento(jTextFieldNomeDepartamento.getText());
            docDao.create(docente);

            limpaCampos();
            lerTabela();
        }
        
        
        
//        DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//        Object[] dados = {jTextFieldCodAluno.getText(),jTextFieldNomeAluno.getText(),
//                          jTextFieldNumAluno.getText(), jTextFieldCursoAluno.getText()};
//        dtmAlunos.addRow(dados);
        
     
    }//GEN-LAST:event_jButtonSalvarDocenteActionPerformed

    public void lerTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTableTabelaDocentes.getModel();
        modelo.setNumRows(0);
        DocenteDao ddao = new DocenteDao();
       
     
        for (ArrayList a: ddao.read2()){
            modelo.addRow(new Object[]{
            a.get(0),
            a.get(1),
            a.get(2),
            a.get(3)
            
        });
    }
    }
    
    private void jButtonExcluirDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirDocenteActionPerformed
        // TODO add your handling code here:
//        if (jTableTabelaAlunos.getSelectedRow() != -1){
//            DefaultTableModel dtmAlunos = (DefaultTableModel)jTableTabelaAlunos.getModel();
//            dtmAlunos.removeRow(jTableTabelaAlunos.getSelectedRow());           
//        }else{
//            JOptionPane.showMessageDialog(null, "Selecione um aluno");
//        }
        
         if (jTableTabelaDocentes.getSelectedRow() != -1){
           
            Pessoa pessoa = new Pessoa();
            PessoaDao pesDao = new PessoaDao();
            Aluno aluno = new Aluno();
            AlunoDao aluDao = new AlunoDao();

            pessoa.setCodPessoa(Integer.parseInt(jTextFieldCodDocente.getText()));
            pesDao.delete(pessoa);

            aluno.setCodPessoa(Integer.parseInt(jTextFieldCodDocente.getText()));
            aluDao.delete(aluno);
            
            limpaCampos();
            lerTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um aluno");
        }        
        
        lerTabela();
               
        
    }//GEN-LAST:event_jButtonExcluirDocenteActionPerformed

    private void jTableTabelaDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaDocentesMouseClicked
        // TODO add your handling code here:
        if (jTableTabelaDocentes.getSelectedRow() != -1){
            jTextFieldCodDocente.setText(jTableTabelaDocentes.getValueAt(jTableTabelaDocentes.getSelectedRow(), 0).toString());
            jTextFieldNomeDocente.setText(jTableTabelaDocentes.getValueAt(jTableTabelaDocentes.getSelectedRow(), 1).toString());
            jTextFieldNumInstituicao.setText(jTableTabelaDocentes.getValueAt(jTableTabelaDocentes.getSelectedRow(), 2).toString());
            jTextFieldNomeDepartamento.setText(jTableTabelaDocentes.getValueAt(jTableTabelaDocentes.getSelectedRow(), 3).toString());
            jLabelCodDocenteAtual.setText(jTableTabelaDocentes.getValueAt(jTableTabelaDocentes.getSelectedRow(), 0).toString());
                          
        }
        
    }//GEN-LAST:event_jTableTabelaDocentesMouseClicked

    private void jButtonAtualizarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDocenteActionPerformed
        // TODO add your handling code here:
        if (jTableTabelaDocentes.getSelectedRow() != -1){
            
            Pessoa pessoa = new Pessoa();
            PessoaDao pesDao = new PessoaDao();
            Docente docente = new Docente();
            DocenteDao docDao = new DocenteDao();

            pessoa.setCodPessoa(Integer.parseInt(jTextFieldCodDocente.getText()));
            pessoa.setNomePessoa(jTextFieldNomeDocente.getText());
            //pessoa.setCodPessoa((int) jTableTabelaAlunos.getValueAt(jTableTabelaAlunos.getSelectedRow(), 0));
            

            docente.setCodPessoa(pessoa.getCodPessoa());
            docente.setCodInstituicao(Integer.parseInt(jTextFieldNumInstituicao.getText()));
            docente.setNomeDepartamento(jTextFieldNomeDepartamento.getText());
            //aluno.setCodPessoa((int) jTableTabelaAlunos.getValueAt(jTableTabelaAlunos.getSelectedRow(), 0));
            int codigo = Integer.parseInt(jLabelCodDocenteAtual.getText());
            
            pesDao.update(pessoa, codigo);
            docDao.update(docente);
            
            limpaCampos();
            lerTabela();
            
//            jTableTabelaAlunos.setValueAt(jTextFieldCodAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 0);
//            jTableTabelaAlunos.setValueAt(jTextFieldNomeAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 1);
//            jTableTabelaAlunos.setValueAt(jTextFieldNumAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 2);
//            jTableTabelaAlunos.setValueAt(jTextFieldCursoAluno.getText(), jTableTabelaAlunos.getSelectedRow(), 3);

        }
        
    }//GEN-LAST:event_jButtonAtualizarDocenteActionPerformed

    private void jTableTabelaDocentesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTabelaDocentesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTabelaDocentesKeyReleased

    private boolean verificaCampos(){
        String campoCodigo = jTextFieldCodDocente.getText();
        String campoNome = jTextFieldNomeDocente.getText();
        String campoNumero = jTextFieldNumInstituicao.getText();
        String campoDepartamento = jTextFieldNomeDepartamento.getText();
        if (campoCodigo.isEmpty() || campoNome.isEmpty() || campoNumero.isEmpty() || campoDepartamento.isEmpty()){
            return true;
        }else{
            return false;
        }
    }
 
    private void limpaCampos(){
        jTextFieldCodDocente.setText("");
        jTextFieldNomeDocente.setText("");
        jTextFieldNomeDepartamento.setText("");
        jTextFieldNumInstituicao.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDocentes().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarDocente;
    private javax.swing.JButton jButtonExcluirDocente;
    private javax.swing.JButton jButtonSalvarDocente;
    private javax.swing.JLabel jLabelCodDocenteAtual;
    private javax.swing.JLabel jLabelCodigoDocente;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelNomeDocente;
    private javax.swing.JLabel jLabelNumInstituicao;
    private javax.swing.JPanel jPanelCrudDocente;
    private javax.swing.JPanel jPanelTabelaDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaDocentes;
    private javax.swing.JTextField jTextFieldCodDocente;
    private javax.swing.JTextField jTextFieldNomeDepartamento;
    private javax.swing.JTextField jTextFieldNomeDocente;
    private javax.swing.JTextField jTextFieldNumInstituicao;
    // End of variables declaration//GEN-END:variables
}
